### ISSUE TITLE
Ember.js Sample code: error when compiling, some dependencies are not found.

### ISSUE THREAD

**Issue by benlizar** [auth0-community/auth0-ember-samples#13]
**Actual result**
After running the command "npm start", some critical warnings are displayed, is not blocking the user to run the demo app, or log in.

**Expected results**
All critical dependencies should be fixed or removed if they are not being used.

![image](https://user-images.githubusercontent.com/36707032/44162511-97f4c080-a08e-11e8-888b-507abc4adf87.png)

**Comment by beardaway** [comment]
Hey there Benjamin!

Sorry for huge delay in response. Unfortunately we do not have internal bandwidth to maintain these repos and still figuring strategy for that. In the meantime we're looking for community contributors to take over. Once we have the strategy established we're get back to it. Closing it for now and thank you for your understanding!
