### ISSUE TITLE
Unused dependencies are triggering a lot of warnings on the demo source. 

### ISSUE THREAD

**Issue by benlizar** [auth0-community/auth0-ember-samples#14]
Actual result
When installing the demo, npm audit is requesting to run the fix command, to solve 3602 vulnerabilities. Including 36 High vulnerabilities.

Expected results
There should be no warning after installing all dependencies with npm install command.

[Results from npm audit]
![image](https://user-images.githubusercontent.com/36707032/44164013-e906b380-a092-11e8-950c-6b3b0f92f10c.png)

**Comment by beardaway** [comment]
Hey there Benjamin!

Sorry for huge delay in response. Unfortunately we do not have internal bandwidth to maintain these repos and still figuring strategy for that. In the meantime we're looking for community contributors to take over. Once we have the strategy established we're get back to it. Closing it for now and thank you for your understanding!
