### ISSUE TITLE
Typo in readme file.

### ISSUE THREAD

**Issue by paulioceano** [auth0-community/auth0-ember-samples#4]
In the readme file, it says:

```bash
npm install
ember serve 
```

and it should be:

```bash
npm install
ember server 
```

AUTH-3351

**Comment by beardaway** [comment]
Hey there @paulioceano!

I've fixed it just now. Sorry for such delay with contribution but we're pretty hammered with the number of questions in our community forum! Gradually trying our best to maintain all repos here!
